# Site settings
title: "Sempiternity"
description: "Una raccolta di pezzi più o meno brevi. Battuti prima a macchina e poi a computer, perché la tecnologia…."
author: Luca Buran
exclude: ['README.md']
version: '2019-01-01'

#baseurl: http://ranbureand.github.io/jots
baseurl: /
permalink: /pezzo/:title/

timezone: Europe/Rome
encoding: utf-8

# Build settings
markdown: kramdown

# Markdown Processors
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..3